name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: python -m tox
